CREATE DATABASE [CONTACTS]
GO

USE[CONTACTS]
GO

CREATE TABLE [CONTACT](

	[IDCONTACTPK]		INT IDENTITY (0, 1),
	[IDCLIENT]			INT	CONSTRAINT FK_CONTACT_IDCLIENT_CLIENT_IDCLIENTPK FOREIGN KEY REFERENCES [CLIENT]([IDCLIENTPK])					NOT NULL,
	[IDEMPLOYEE]		INT	CONSTRAINT FK_CONTACT_IDEMPLOYEE_EMPLOYEE_IDEMPLOYEEPK FOREIGN KEY REFERENCES [EMPLOYEE]([IDEMPLOYEEPK])		NOT NULL,
	[IDTOUR]			INT	CONSTRAINT FK_CONTACT_IDTOUR_TOUR_IDTOURPK  FOREIGN KEY REFERENCES [TOUR]([IDTOURPK])							NOT NULL,
	CONSTRAINT PK_CONTACT_IDCONTACTPK PRIMARY KEY ([IDCONTACTPK])
)
GO

CREATE TABLE [CLIENT](
		
	[IDCLIENTPK]		INT IDENTITY(0, 1),
	[FIRSTNAME]			NVARCHAR(MAX)			NOT NULL,
	[LASTNAME]			NVARCHAR(MAX)			NOT NULL,
	[MIDDLENAME]		NVARCHAR(MAX)			NOT NULL,
	[IDTOUR]			INT	CONSTRAINT FK_CLIENT_IDTOUR_TOUR_IDTOURPK FOREIGN KEY REFERENCES [TOUR]([IDTOURPK])								NOT NULL,
	CONSTRAINT PK_CLIENT_IDCLIENTPK PRIMARY KEY ([IDCLIENTPK])
)
GO

CREATE TABLE [EMPLOYEE](

	[IDEMPLOYEEPK]		INT IDENTITY(0, 1),
	[FIRSTNAME]			NVARCHAR(MAX)			NOT NULL,
	[LASTNAME]			NVARCHAR(MAX)			NOT NULL,
	[MIDDLENAME]		NVARCHAR(MAX)			NOT NULL,
	[IDPOSITION]		INT	CONSTRAINT FK_EMPLOYEE_IDPOSITION_POSITION_IDPOSITIONPK  FOREIGN KEY REFERENCES [POSITION]([IDPOSITIONPK])		NOT NULL,
	CONSTRAINT PK_EMPLOYEE_IDEMPLOYEEPK PRIMARY KEY ([IDEMPLOYEEPK])
)
GO

CREATE TABLE [POSITION](

	[IDPOSITIONPK]		INT IDENTITY(0, 1),
	[TITLE]				NVARCHAR(MAX)			NOT NULL,
	CONSTRAINT PK_POSITION_IDPOSITIONPK PRIMARY KEY ([IDPOSITIONPK])
)
GO

CREATE TABLE [TOUR](

	[IDTOURPK]			INT IDENTITY(0, 1),
	[TITLE]				NVARCHAR(MAX)			NOT NULL,
	[PRICE]				NVARCHAR(MAX)			NOT NULL,
	CONSTRAINT PK_TOUR_IDTOURPK PRIMARY KEY ([IDTOURPK])
)
GO

CREATE TABLE [PASSPORT](
	
	[IDPASSPORTPK]		INT IDENTITY(0, 1),
	[REGION]			NVARCHAR(MAX)			NOT NULL,
	[NUMBER]			NVARCHAR(MAX)			NOT NULL,
	[SERIES]			NVARCHAR(MAX)			NOT NULL,
	[DATE]				DATE					NOT NULL,
	[IDCLIENT]			INT	CONSTRAINT FK_PASSPORT_IDCLIENT_CLIENT_IDCLIENTPK  FOREIGN KEY REFERENCES [CLIENT]([IDCLIENTPK])				NOT NULL,
	CONSTRAINT PK_PASSPORT_IDPASSPORTPK PRIMARY KEY ([IDPASSPORTPK])
)
GO